version: '3.7'

services:
  nginx:
    image: docker.pkg.github.com/evoja/git-auto-deploy-to-docker/example-nginx:${TAG}
    ports:
      - target: 80
        published: 9001
        protocol: tcp
        mode: ingress
