name: Build example Python server
on:
  push:
    tags:
      - ep/*
jobs:
  push-python:
    name: Push Example Python Server Docker image to GitHub Packages
    runs-on: ubuntu-latest
    if: ${{startsWith(github.ref, 'refs/tags/ep/')}}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Calculate environments
        run: |
          echo IMAGE_REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo IMAGE_TAG=$(./image-gad2d/docker-tag.sh ${{github.ref}}) >> $GITHUB_ENV
      - name: Calculate images full names
        run: |
          echo IMAGE=docker.pkg.github.com/$IMAGE_REPO/example-python:$IMAGE_TAG >> $GITHUB_ENV
      - name: Login to GitHub Packages Docker Registry
        run: |
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: Build content image
        run: |
          docker build \
              --rm \
              -f example/image-python/Dockerfile \
              -t $IMAGE \
              example/image-python
      - name: Push to GitHub Packages
        run: |
          docker push $IMAGE
