name: Build example Nginx server
on:
  push:
    tags:
      - en/*
jobs:
  push-nginx:
    name: Push Example Nginx Server Docker image to GitHub Packages
    runs-on: ubuntu-latest
    if: ${{startsWith(github.ref, 'refs/tags/en/')}}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Calculate environments
        run: |
          echo IMAGE_REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo IMAGE_TAG=$(./.github/workflows/docker-tag.sh ${{github.ref}}) >> $GITHUB_ENV

      - name: Calculate images full names
        run: |
          echo IMAGE=docker.pkg.github.com/$IMAGE_REPO/example-nginx:$IMAGE_TAG >> $GITHUB_ENV

      - name: Login to GitHub Packages Docker Registry
        run: |
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build content image
        run: |
          docker build \
              --rm \
              -f example/image-nginx/Dockerfile \
              -t $IMAGE \
              example/image-nginx

      - name: Push to GitHub Packages
        run: |
          docker push $IMAGE


