name: Build "Init Secrets" image
on:
  push:
    branches:
      - master
      - dev*
    tags:
      - init-secrets/*

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    env:
      IMAGE_PUSH: >-
        ${{
          startsWith(github.ref, 'refs/tags/init-secrets/')
          || github.ref == 'refs/heads/master'
          || endsWith(github.ref, '-push')
        }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Show docker and docker-compose versions
        run: |
          docker --version
          docker-compose --version

      - name: Calculate environments
        run: |
          echo IMAGE_REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo IMAGE_TAG=$(./image-gad2d/docker-tag.sh ${{github.ref}}) >> $GITHUB_ENV

      - name: Calculate images full names
        run: |
          echo IMAGE=docker.pkg.github.com/$IMAGE_REPO/gad2d-init-secrets:$IMAGE_TAG >> $GITHUB_ENV

      - name: Login to GitHub Packages Docker Registry
        run: |
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build \
              --rm \
              -f image-init-secrets/Dockerfile \
              -t $IMAGE \
              image-init-secrets

      - name: Push to GitHub Packages
        if: ${{ env.IMAGE_PUSH == 'true' }}
        run: |
          docker push $IMAGE
